# Generated by Django 3.0.6 on 2020-05-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('text', models.TextField()),
                ('time_to_read', models.IntegerField(choices=[(1, '<= 1 day'), (2, '<= 1 week'), (3, '<= 1 month'), (4, '<= 6 month'), (5, '<= 1 year')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed lesson', max_length=254)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('text', models.TextField(blank=True)),
                ('video', models.CharField(max_length=254, null=True)),
                ('materials', models.CharField(max_length=254, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Course')),
            ],
        ),
    ]
