# Generated by Django 3.0.7 on 2020-06-09 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('alias', models.CharField(max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(null=True)),
                ('title', models.CharField(max_length=254)),
                ('text', models.TextField()),
                ('time_to_read', models.PositiveSmallIntegerField(choices=[(1, '<= 1 day'), (2, '<= 1 week'), (3, '<= 1 month'), (4, '<= 6 month'), (5, '<= 1 year')], default=3)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD')], default=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed lesson', max_length=254)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('text', models.TextField(blank=True)),
                ('video', models.FileField(null=True, upload_to='')),
                ('stream_url', models.URLField(null=True)),
                ('materials', models.URLField(null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='courses.Lesson')),
            ],
        ),
    ]
