# Generated by Django 3.0.6 on 2020-05-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD'), (4, 'IMPOSSIBLE')], default=2),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_live',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stream_url',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_cancelled',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson'),
        ),
    ]
