# Generated by Django 3.2.4 on 2021-07-30 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210730_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 30, 14, 39, 26, 444580, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
