# Generated by Django 3.0.6 on 2020-05-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200519_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD')], default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_to_read',
            field=models.PositiveSmallIntegerField(choices=[(1, '<= 1 day'), (2, '<= 1 week'), (3, '<= 1 month'), (4, '<= 6 month'), (5, '<= 1 year')], default=2),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='stream_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='courses.Lesson'),
        ),
    ]
