# Generated by Django 3.0.6 on 2020-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200521_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
