# Generated by Django 3.0.7 on 2020-08-06 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200609_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 18, 0, 1, 561234, tzinfo=utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, verbose_name='Что Вы хотите написать'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=254, verbose_name='Заголовок'),
        ),
    ]
