# Generated by Django 3.0.7 on 2020-08-15 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200806_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
    ]
